<?php

namespace AppBundle\Entity\Repository;

/**
 * TAutorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TAutorRepository extends \Doctrine\ORM\EntityRepository
{
}
