<?php

namespace AppBundle\Entity\Repository;

/**
 * TMaterialLivroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TMaterialLivroRepository extends \Doctrine\ORM\EntityRepository
{
}
