<?php

namespace AppBundle\Entity\Repository;

/**
 * TMaterialDicionarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TMaterialDicionarioRepository extends \Doctrine\ORM\EntityRepository
{
}
